/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.noitom.pnstream;

import com.noitom.pnstream.server.ServerApp;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ServerApp classUnderTest = new ServerApp();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
